name: khyate_tailor_app
description: "Step into style with this mobile app, seamlessly connecting you to UAE's finest tailors for traditional attire, from bespoke designs to perfect alterations."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_spinkit: any
  lottie: any
  carousel_slider: any
  dropdown_button2: any
  flutter_widget_from_html: any
  flutter_screenutil : any

  # State Management & Utils
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^7.7.0

  # Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.4

  # Network & API
  dio: ^5.7.0
  http: ^1.2.1
  retrofit: ^4.4.1
  socket_io_client: ^2.0.3+1

  # Firebase
  firebase_core: any
  firebase_auth: any
  firebase_messaging: any
  cloud_firestore: any
  flutter_facebook_auth: any
  google_sign_in: any

  # Media & Files
  cached_network_image: any
  image_picker: any
  file_picker: ^10.2.0
  open_file: any
  path: any
  path_provider: any
  pdf: any

  # Location & Maps
  geolocator: ^10.1.0
  geocoding: any
  location: any
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  flutter_polyline_points: any
  latlong2: ^0.9.0

  # Notifications & Local Auth
  flutter_local_notifications: any
  local_auth: ^2.1.7

  # Payments
  flutter_stripe: ^10.0.0

  # Animation
  flutter_animate: ^4.3.0

  # Device
  connectivity_plus: ^6.1.0
  device_info_plus: any

  # Misc
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: any
  webview_flutter: ^4.4.2
  audioplayers: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  # flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/khyate_logo.png
